import { getInterviewReplay } from "@/lib/replay";

const escapePdf = (value: string) => value.replace(/[^\x20-\x7E]/g, " ").replace(/([\\()])/g, "\\$1");
function createPdf(title: string, lines: string[]) {
  const pages = Array.from({ length: Math.max(1, Math.ceil(lines.length / 42)) }, (_, index) => lines.slice(index * 42, index * 42 + 42));
  const objects: string[] = ["<< /Type /Catalog /Pages 2 0 R >>", `<< /Type /Pages /Kids [${pages.map((_, i) => `${4 + i * 2} 0 R`).join(" ")}] /Count ${pages.length} >>`, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"];
  pages.forEach((page, index) => { const pageId=4+index*2; const contentId=pageId+1; const text=[`BT /F1 16 Tf 50 790 Td (${escapePdf(title)}) Tj`,`0 -28 Td /F1 10 Tf`,...page.map(line=>`(${escapePdf(line).slice(0,110)}) Tj 0 -16 Td`),"ET"].join("\n"); objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`, `<< /Length ${Buffer.byteLength(text)} >>\nstream\n${text}\nendstream`); });
  let pdf="%PDF-1.4\n"; const offsets=[0]; objects.forEach((obj,i)=>{ offsets[i+1]=Buffer.byteLength(pdf); pdf+=`${i+1} 0 obj\n${obj}\nendobj\n`; }); const xref=Buffer.byteLength(pdf); pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(o=>`${o.toString().padStart(10,"0")} 00000 n `).join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`; return Buffer.from(pdf);
}
export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) { const {id}=await params; const replay=await getInterviewReplay(id); if(!replay) return new Response("Not found",{status:404}); const url=new URL(request.url); const type=url.searchParams.get("type")==="feedback"?"feedback":"transcript"; const format=url.searchParams.get("format")==="txt"?"txt":"pdf"; const lines=type==="feedback"?[`Score: ${replay.score ?? "N/A"}`, JSON.stringify(replay.feedback ?? {},null,2)]:replay.transcript.map(item=>`${Math.floor(item.timestamp/60).toString().padStart(2,"0")}:${Math.floor(item.timestamp%60).toString().padStart(2,"0")} ${item.role==="assistant"?"AI":"Candidate"}: ${item.content}`); const body=format==="txt"?Buffer.from(lines.join("\n\n")):createPdf(type==="feedback"?"Interview Feedback":"Interview Transcript",lines); return new Response(body,{headers:{"Content-Type":format==="txt"?"text/plain; charset=utf-8":"application/pdf","Content-Disposition":`attachment; filename="interview-${type}.${format}"`}}); }
